### ISSUE TITLE
I see you have a plan to create 3D, I'm not sure how to implement it

### ISSUE THREAD

**Issue by asmwarrior** [DanielMartensson/wxPlot#2]
Your project is nice, I see some posts of your in wxWidgets forum, and linked here.

Do you use OpenGL?

BTW, for 2D plot under wxWidgets, there are some components:

[GitHubLionel/wxMathPlot: An enhanced version of the wxMathPlot component for wxWidgets](https://github.com/GitHubLionel/wxMathPlot)

[Blake-Madden/Wisteria-Dataviz: Wisteria Dataviz Library](https://github.com/Blake-Madden/Wisteria-Dataviz)

for 3D, I see this:
[ABRG-Models/morphologica: C++ header-only graphing and data visualization with Modern OpenGL](https://github.com/ABRG-Models/morphologica), and I have made some contribution to it, but it looks like this is a bit slow.

Also, see [markaren/threepp: C++20 port of three.js (r129)](https://github.com/markaren/threepp), I can also have this component works under wxWidgets.

also, this one: [visualizationlibrary library now in msys2 packages which has wxWidgets gui support - wxWidgets Discussion Forum](https://forums.wxwidgets.org/viewtopic.php?f=10&t=50576)

**Comment by DanielMartensson** [comment]
> Your project is nice, I see some posts of your in wxWidgets forum, and linked here.
> 
> Do you use OpenGL?
> 
> BTW, for 2D plot under wxWidgets, there are some components:
> 
> [GitHubLionel/wxMathPlot: An enhanced version of the wxMathPlot component for wxWidgets](https://github.com/GitHubLionel/wxMathPlot)
> 
> [Blake-Madden/Wisteria-Dataviz: Wisteria Dataviz Library](https://github.com/Blake-Madden/Wisteria-Dataviz)
> 
> for 3D, I see this: [ABRG-Models/morphologica: C++ header-only graphing and data visualization with Modern OpenGL](https://github.com/ABRG-Models/morphologica), and I have made some contribution to it, but it looks like this is a bit slow.
> 
> Also, see [markaren/threepp: C++20 port of three.js (r129)](https://github.com/markaren/threepp), I can also have this component works under wxWidgets.
> 
> also, this one: [visualizationlibrary library now in msys2 packages which has wxWidgets gui support - wxWidgets Discussion Forum](https://forums.wxwidgets.org/viewtopic.php?f=10&t=50576)

@asmwarrior 

Hi!
Thank you for your question.

No, I don't use OpenGL. wxPlot is 100% portable and only require wxWidgets. No other libs.

The purpose of this library is to run it in real time. Thave you tried it?

If you want to build some 3D features to this library
 Please send a PR. Could you make so you only use wxWidgets like polygon to create a 3D?

I mean, displaying a 3D chart can be done using simple 2D tools and it still will run fast.

**Comment by asmwarrior** [comment]
> 
> No, I don't use OpenGL. wxPlot is 100% portable and only require wxWidgets. No other libs.
> 

 I just build this library today. I found that when the plot is shown, I don't know how to zoom or pan the plot window, so, this may be a feature request.


> The purpose of this library is to run it in real time. Thave you tried it?
> 

Yes, I have just tried today.

> If you want to build some 3D features to this library Please send a PR. Could you make so you only use wxWidgets like polygon to create a 3D?
> 
> I mean, displaying a 3D chart can be done using simple 2D tools and it still will run fast.

I think if you want to draw 3D plots, you need to use some libraries such as OpenGL, and wxWidgets natively support OpenGL, you can see the OpenGL wxWidgets samples. I don't think the real time 3D plot can be implemented without those OpenGL or other similar libraries. Because you need GPU acceleration of showing those 3D plots.

BTW: I have create a PR, and I think the `obj` files should be removed from the code repo.

**Comment by DanielMartensson** [comment]
@asmwarrior 

Thank you. Can you send a PR for 3D as well ? 

Just read this code:
https://github.com/DanielMartensson/wxPlot/blob/main/wxPlot/src/plots/plotfigures/2D/proportional/proportional.cpp

This code draws the rectangle, ticks and labels, and grid and also re-compute the rectangle if X-label, title, Y-label are being used.

Do the same with 3D. You can 75% use public inheritance on that class for 3D.

**Comment by asmwarrior** [comment]
Oh, drawing in 3D, for example is complex under OpenGL, I have no idea how to do that. Have you ever tried some OpenGL program? It is much complex than drawing in 2D.

**Comment by DanielMartensson** [comment]
@asmwarrior 
Thank you for the conversation!
